
export const GET_PRODUCT_PAGE_LIST = 'GET_PRODUCT_PAGE_LIST';
export const GET_PRODUCT_DETAIL='GET_PRODUCT_DETAIL';
export const ADD_TO_CART='ADD_TO_CART';
export const DELETE_PRODUCT_CART='DELETE_PRODUCT_CART';
export const CHANGE_MESSAGE ='CHANGE_MESSAGE';
export const CHANGE_LABEL ='CHANGE_LABEL';
export const UPDATE_PRODUCT_QUANTITY ='UPDATE_PRODUCT_QUANTITY';